bind_to_address "127.0.0.1"
port "41122"

music_directory "/home/alan/Media/Music/Phonks"
playlist_directory "/home/alan/.config/mpd/playlists"
db_file "/home/alan/.config/mpd/db"
log_file "/tmp/logmpd"
pid_file "/home/alan/.config/mpd/pid"
state_file "/home/alan/.config/mpd/state"
auto_update "yes"
auto_update_depth "2"

audio_output {
    type "pulse"
    name "default"
    options "software"
}

audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}